// central place to hold questions for every sub-topic
export const practiceBank = {
    // key = "grammar-tenses"  (match the slug you created in router.push)
    "grammar": [
      { q: "She _____ to school every day.",  opts: ["go", "goes", "is going", "gone"],  ans: 1 },
      { q: "Right now they _____ football.",  opts: ["play", "played", "are playing", "plays"], ans: 2 },
      { q: "I _____ my homework before dinner yesterday.", opts: ["finish", "finished", "had finished", "finishing"], ans: 2 },
      { q: "By the time she arrived, we _____ eating.", opts: ["were", "had finished", "have finished", "finish"], ans: 1 },
      { q: "He _____ in London since 2010.", opts: ["lives", "lived", "has lived", "is living"], ans: 2 },
      { q: "They _____ to the museum tomorrow.", opts: ["go", "went", "are going", "have gone"], ans: 2 },
      { q: "We _____ dinner when the phone rang.", opts: ["have", "had", "were having", "are having"], ans: 2 },
      { q: "She _____ her keys, so she can't open the door.", opts: ["loses", "lost", "has lost", "had lost"], ans: 2 },
      { q: "When I was young, I _____ to the park every day.", opts: ["go", "went", "was going", "gone"], ans: 1 },
      { q: "He _____ already left when I arrived.", opts: ["had", "has", "was", "did"], ans: 0 },
      { q: "She _____ her book when the teacher came in.", opts: ["reads", "read", "was reading", "has read"], ans: 2 },
      { q: "We _____ our exams by next week.", opts: ["finish", "will finish", "have finished", "will have finished"], ans: 3 },
      { q: "The cat is _____ the table.", opts: ["on", "in", "at", "by"], ans: 0 },
      { q: "He arrived _____ the airport at 6 PM.", opts: ["on", "to", "in", "at"], ans: 3 },
      { q: "She walked _____ the room.", opts: ["into", "onto", "under", "about"], ans: 0 },
      { q: "They went _____ vacation last week.", opts: ["in", "at", "on", "to"], ans: 2 },
      { q: "He sat _____ her during the concert.", opts: ["beside", "behind", "under", "above"], ans: 0 },
      { q: "The book is _____ the bag.", opts: ["in", "on", "at", "into"], ans: 0 },
      { q: "She jumped _____ the river.", opts: ["into", "in", "onto", "on"], ans: 0 },
      { q: "He lives _____ Dubai.", opts: ["on", "at", "in", "to"], ans: 2 },
      { q: "She works _____ a tech company.", opts: ["in", "at", "on", "to"], ans: 1 },
      { q: "He was born _____ 2005.", opts: ["at", "in", "on", "to"], ans: 1 },
      { q: "We’ll meet _____ Friday.", opts: ["in", "on", "at", "by"], ans: 1 },
      { q: "He put the book _____ the table.", opts: ["in", "into", "on", "onto"], ans: 2 },
      { q: "They arrived _____ the same time.", opts: ["in", "on", "at", "by"], ans: 2 },
      { q: "She stood _____ the window and watched the rain.", opts: ["by", "under", "above", "on"], ans: 0 },
      { q: "We walked _____ the bridge.", opts: ["through", "across", "between", "into"], ans: 1 },
      { q: "I saw _____ elephant at the zoo.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "She wants to buy _____ umbrella.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "_____ moon looks beautiful tonight.", opts: ["A", "An", "The", "No article"], ans: 2 },
      { q: "He is _____ honest man.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "They found _____ old map.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "Do you have _____ pen I can borrow?", opts: ["a", "an", "the", "no article"], ans: 0 },
      { q: "We went to _____ beach yesterday.", opts: ["a", "an", "the", "no article"], ans: 2 },
      { q: "I don’t like _____ milk.", opts: ["a", "an", "the", "no article"], ans: 3 },
      { q: "_____ earth revolves around the sun.", opts: ["A", "An", "The", "No article"], ans: 2 },
      { q: "She has _____ idea!", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "He is _____ best player in the team.", opts: ["a", "an", "the", "no article"], ans: 2 },
      { q: "_____ apple a day keeps the doctor away.", opts: ["A", "An", "The", "No article"], ans: 0 },
      { q: "I read _____ interesting story.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "She lives near _____ university.", opts: ["a", "an", "the", "no article"], ans: 0 },
      { q: "I met _____ old friend yesterday.", opts: ["a", "an", "the", "no article"], ans: 0 },
      { q: "_____ is my best friend.", opts: ["He", "Him", "His", "Me"], ans: 0 },
      { q: "Give the book to _____.", opts: ["I", "me", "mine", "my"], ans: 1 },
      { q: "This pen is _____.", opts: ["me", "mine", "my", "I"], ans: 1 },
      { q: "_____ are going to the mall.", opts: ["Them", "They", "Their", "Theirs"], ans: 1 },
      { q: "Is this gift for _____?", opts: ["she", "her", "hers", "his"], ans: 1 },
      { q: "That’s not your bag, it’s _____.", opts: ["my", "mine", "me", "I"], ans: 1 },
      { q: "The dog wagged _____ tail.", opts: ["its", "it’s", "his", "her"], ans: 0 },
      { q: "_____ am learning to cook.", opts: ["Me", "I", "Mine", "My"], ans: 1 },
      { q: "They gave the invitation to you and _____.", opts: ["I", "me", "mine", "myself"], ans: 1 },
      { q: "Can you help _____ carry these boxes?", opts: ["us", "we", "our", "ours"], ans: 0 },
      { q: "Is this jacket _____?", opts: ["your", "yours", "you", "you're"], ans: 1 },
      { q: "John and _____ are going together.", opts: ["me", "mine", "I", "my"], ans: 2 },
      { q: "Tell him to do it by _____.", opts: ["him", "himself", "he", "his"], ans: 1 },
      { q: "Everyone brought _____ own lunch.", opts: ["their", "his", "our", "her"], ans: 0 },
      { q: "Neither of the boys did _____ homework.", opts: ["their", "his", "her", "our"], ans: 1 }
    ],
    "grammar-tenses": [
      { q: "She _____ to school every day.",  opts: ["go", "goes", "is going", "gone"],  ans: 1 },
      { q: "Right now they _____ football.",  opts: ["play", "played", "are playing", "plays"], ans: 2 },
      { q: "I _____ my homework before dinner yesterday.", opts: ["finish", "finished", "had finished", "finishing"], ans: 2 },
      { q: "By the time she arrived, we _____ eating.", opts: ["were", "had finished", "have finished", "finish"], ans: 1 },
      { q: "He _____ in London since 2010.", opts: ["lives", "lived", "has lived", "is living"], ans: 2 },
      { q: "They _____ to the museum tomorrow.", opts: ["go", "went", "are going", "have gone"], ans: 2 },
      { q: "We _____ dinner when the phone rang.", opts: ["have", "had", "were having", "are having"], ans: 2 },
      { q: "She _____ her keys, so she can't open the door.", opts: ["loses", "lost", "has lost", "had lost"], ans: 2 },
      { q: "When I was young, I _____ to the park every day.", opts: ["go", "went", "was going", "gone"], ans: 1 },
      { q: "He _____ already left when I arrived.", opts: ["had", "has", "was", "did"], ans: 0 },
      { q: "She _____ her book when the teacher came in.", opts: ["reads", "read", "was reading", "has read"], ans: 2 },
      { q: "We _____ our exams by next week.", opts: ["finish", "will finish", "have finished", "will have finished"], ans: 3 }
      
    ],
    "grammar-prepositions":  [
      { q: "The cat is _____ the table.", opts: ["on", "in", "at", "by"], ans: 0 },
      { q: "He arrived _____ the airport at 6 PM.", opts: ["on", "to", "in", "at"], ans: 3 },
      { q: "She walked _____ the room.", opts: ["into", "onto", "under", "about"], ans: 0 },
      { q: "They went _____ vacation last week.", opts: ["in", "at", "on", "to"], ans: 2 },
      { q: "He sat _____ her during the concert.", opts: ["beside", "behind", "under", "above"], ans: 0 },
      { q: "The book is _____ the bag.", opts: ["in", "on", "at", "into"], ans: 0 },
      { q: "She jumped _____ the river.", opts: ["into", "in", "onto", "on"], ans: 0 },
      { q: "He lives _____ Dubai.", opts: ["on", "at", "in", "to"], ans: 2 },
      { q: "She works _____ a tech company.", opts: ["in", "at", "on", "to"], ans: 1 },
      { q: "He was born _____ 2005.", opts: ["at", "in", "on", "to"], ans: 1 },
      { q: "We’ll meet _____ Friday.", opts: ["in", "on", "at", "by"], ans: 1 },
      { q: "He put the book _____ the table.", opts: ["in", "into", "on", "onto"], ans: 2 },
      { q: "They arrived _____ the same time.", opts: ["in", "on", "at", "by"], ans: 2 },
      { q: "She stood _____ the window and watched the rain.", opts: ["by", "under", "above", "on"], ans: 0 },
      { q: "We walked _____ the bridge.", opts: ["through", "across", "between", "into"], ans: 1 }
    
    ],
    "grammar-articles": [
      { q: "I saw _____ elephant at the zoo.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "She wants to buy _____ umbrella.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "_____ moon looks beautiful tonight.", opts: ["A", "An", "The", "No article"], ans: 2 },
      { q: "He is _____ honest man.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "They found _____ old map.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "Do you have _____ pen I can borrow?", opts: ["a", "an", "the", "no article"], ans: 0 },
      { q: "We went to _____ beach yesterday.", opts: ["a", "an", "the", "no article"], ans: 2 },
      { q: "I don’t like _____ milk.", opts: ["a", "an", "the", "no article"], ans: 3 },
      { q: "_____ earth revolves around the sun.", opts: ["A", "An", "The", "No article"], ans: 2 },
      { q: "She has _____ idea!", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "He is _____ best player in the team.", opts: ["a", "an", "the", "no article"], ans: 2 },
      { q: "_____ apple a day keeps the doctor away.", opts: ["A", "An", "The", "No article"], ans: 0 },
      { q: "I read _____ interesting story.", opts: ["a", "an", "the", "no article"], ans: 1 },
      { q: "She lives near _____ university.", opts: ["a", "an", "the", "no article"], ans: 0 },
      { q: "I met _____ old friend yesterday.", opts: ["a", "an", "the", "no article"], ans: 0 }
    ],
    "grammar-pronouns":[
      { q: "_____ is my best friend.", opts: ["He", "Him", "His", "Me"], ans: 0 },
      { q: "Give the book to _____.", opts: ["I", "me", "mine", "my"], ans: 1 },
      { q: "This pen is _____.", opts: ["me", "mine", "my", "I"], ans: 1 },
      { q: "_____ are going to the mall.", opts: ["Them", "They", "Their", "Theirs"], ans: 1 },
      { q: "Is this gift for _____?", opts: ["she", "her", "hers", "his"], ans: 1 },
      { q: "That’s not your bag, it’s _____.", opts: ["my", "mine", "me", "I"], ans: 1 },
      { q: "The dog wagged _____ tail.", opts: ["its", "it’s", "his", "her"], ans: 0 },
      { q: "_____ am learning to cook.", opts: ["Me", "I", "Mine", "My"], ans: 1 },
      { q: "They gave the invitation to you and _____.", opts: ["I", "me", "mine", "myself"], ans: 1 },
      { q: "Can you help _____ carry these boxes?", opts: ["us", "we", "our", "ours"], ans: 0 },
      { q: "Is this jacket _____?", opts: ["your", "yours", "you", "you're"], ans: 1 },
      { q: "John and _____ are going together.", opts: ["me", "mine", "I", "my"], ans: 2 },
      { q: "Tell him to do it by _____.", opts: ["him", "himself", "he", "his"], ans: 1 },
      { q: "Everyone brought _____ own lunch.", opts: ["their", "his", "our", "her"], ans: 0 },
      { q: "Neither of the boys did _____ homework.", opts: ["their", "his", "her", "our"], ans: 1 }
    ],
    
    "vocabulary": [
      { q: "Select the synonym of 'happy'.", opts: ["sad", "joyful", "angry", "bored"], ans: 1 },
      { q: "Select the antonym of 'brave'.", opts: ["bold", "fearless", "cowardly", "strong"], ans: 2 },
      { q: "Select the synonym of 'begin'.", opts: ["end", "start", "close", "exit"], ans: 1 },
      { q: "Select the antonym of 'light'.", opts: ["heavy", "bright", "soft", "quick"], ans: 0 },
      { q: "Select the synonym of 'angry'.", opts: ["calm", "peaceful", "furious", "gentle"], ans: 2 },
      { q: "Select the antonym of 'cheap'.", opts: ["expensive", "free", "old", "rare"], ans: 0 },
      { q: "Select the synonym of 'small'.", opts: ["tiny", "huge", "tall", "loud"], ans: 0 },
      { q: "Select the antonym of 'beautiful'.", opts: ["gorgeous", "ugly", "charming", "pretty"], ans: 1 },
      { q: "Select the synonym of 'fast'.", opts: ["quick", "slow", "weak", "silent"], ans: 0 },
      { q: "Select the antonym of 'rich'.", opts: ["wealthy", "famous", "poor", "strong"], ans: 2 },
      { q: "Select the synonym of 'help'.", opts: ["ignore", "assist", "argue", "avoid"], ans: 1 },
      { q: "Select the antonym of 'early'.", opts: ["first", "late", "soon", "quick"], ans: 1 },
      { q: "Select the synonym of 'tired'.", opts: ["sleepy", "awake", "active", "fresh"], ans: 0 },
      { q: "Select the antonym of 'noisy'.", opts: ["quiet", "loud", "annoying", "rowdy"], ans: 0 },
      { q: "Select the synonym of 'easy'.", opts: ["hard", "simple", "long", "boring"], ans: 1 },
      { q: "Choose the correct noun form of 'decide'.", opts: ["decision", "deciding", "decisive", "decided"], ans: 0 },
      { q: "Choose the adjective form of 'danger'.", opts: ["danger", "dangerous", "endanger", "dangerously"], ans: 1 },
      { q: "Choose the verb form of 'movement'.", opts: ["move", "moving", "moved", "moves"], ans: 0 },
      { q: "Choose the noun form of 'perform'.", opts: ["performance", "performer", "performing", "performs"], ans: 0 },
      { q: "Choose the adjective form of 'beauty'.", opts: ["beautiful", "beautify", "beautified", "beauty"], ans: 0 },
      { q: "Choose the adverb form of 'quick'.", opts: ["quicker", "quickness", "quickly", "quicken"], ans: 2 },
      { q: "Choose the verb form of 'discussion'.", opts: ["discuss", "discussing", "discussed", "discusses"], ans: 0 },
      { q: "Choose the noun form of 'educate'.", opts: ["education", "educating", "educated", "educator"], ans: 0 },
      { q: "Choose the adjective form of 'health'.", opts: ["heal", "healthy", "healthily", "healthful"], ans: 1 },
      { q: "Choose the noun form of 'grow'.", opts: ["grown", "grew", "growth", "growing"], ans: 2 },
      { q: "Choose the adverb form of 'happy'.", opts: ["happiness", "happily", "happier", "happy"], ans: 1 },
      { q: "Choose the adjective form of 'create'.", opts: ["creative", "creation", "creator", "creatively"], ans: 0 },
      { q: "Choose the noun form of 'strong'.", opts: ["strength", "stronger", "strongly", "strongest"], ans: 0 },
      { q: "Choose the verb form of 'speech'.", opts: ["speak", "spoken", "speaking", "speaks"], ans: 0 },
      { q: "Choose the adjective form of 'music'.", opts: ["musical", "musician", "musically", "music"], ans: 0 },
      { q: "I need to _____ my homework before dinner.", opts: ["give up", "take off", "finish up", "look after"], ans: 2 },
      { q: "She looks _____ her younger brother.", opts: ["at", "after", "over", "through"], ans: 1 },
      { q: "Please _____ the lights when you leave.", opts: ["turn off", "put down", "get off", "take out"], ans: 0 },
      { q: "He _____ smoking last year.", opts: ["gave away", "gave up", "got out", "went off"], ans: 1 },
      { q: "Let’s _____ the problem together.", opts: ["work out", "set off", "turn in", "put up"], ans: 0 },
      { q: "We need to _____ early to catch the train.", opts: ["set out", "run away", "break down", "call off"], ans: 0 },
      { q: "Can you _____ the form, please?", opts: ["fill in", "write off", "go over", "break in"], ans: 0 },
      { q: "He _____ a new idea during the meeting.", opts: ["got through", "came up with", "fell behind", "turned out"], ans: 1 },
      { q: "Don’t _____ your dreams!", opts: ["give up", "go on", "get by", "turn up"], ans: 0 },
      { q: "We ran _____ sugar, so I went to buy some.", opts: ["in", "on", "out of", "down"], ans: 2 },
      { q: "The plane will _____ in 30 minutes.", opts: ["take off", "turn up", "check in", "set up"], ans: 0 },
      { q: "I _____ my old school friend at the mall.", opts: ["ran into", "took over", "got through", "came across"], ans: 0 },
      { q: "Please _____ your shoes before entering.", opts: ["take off", "put out", "get on", "hand in"], ans: 0 },
      { q: "He _____ the challenge and succeeded.", opts: ["came over", "took on", "looked into", "ran over"], ans: 1 },
      { q: "We had to _____ the event due to rain.", opts: ["call off", "get on", "carry on", "put off"], ans: 0 }

    ],
    "vocab-synonyms-&-antonyms": [
      { q: "Select the synonym of 'happy'.", opts: ["sad", "joyful", "angry", "bored"], ans: 1 },
      { q: "Select the antonym of 'brave'.", opts: ["bold", "fearless", "cowardly", "strong"], ans: 2 },
      { q: "Select the synonym of 'begin'.", opts: ["end", "start", "close", "exit"], ans: 1 },
      { q: "Select the antonym of 'light'.", opts: ["heavy", "bright", "soft", "quick"], ans: 0 },
      { q: "Select the synonym of 'angry'.", opts: ["calm", "peaceful", "furious", "gentle"], ans: 2 },
      { q: "Select the antonym of 'cheap'.", opts: ["expensive", "free", "old", "rare"], ans: 0 },
      { q: "Select the synonym of 'small'.", opts: ["tiny", "huge", "tall", "loud"], ans: 0 },
      { q: "Select the antonym of 'beautiful'.", opts: ["gorgeous", "ugly", "charming", "pretty"], ans: 1 },
      { q: "Select the synonym of 'fast'.", opts: ["quick", "slow", "weak", "silent"], ans: 0 },
      { q: "Select the antonym of 'rich'.", opts: ["wealthy", "famous", "poor", "strong"], ans: 2 },
      { q: "Select the synonym of 'help'.", opts: ["ignore", "assist", "argue", "avoid"], ans: 1 },
      { q: "Select the antonym of 'early'.", opts: ["first", "late", "soon", "quick"], ans: 1 },
      { q: "Select the synonym of 'tired'.", opts: ["sleepy", "awake", "active", "fresh"], ans: 0 },
      { q: "Select the antonym of 'noisy'.", opts: ["quiet", "loud", "annoying", "rowdy"], ans: 0 },
      { q: "Select the synonym of 'easy'.", opts: ["hard", "simple", "long", "boring"], ans: 1 }
    ],
    "vocab-word-families": [
      { q: "Choose the correct noun form of 'decide'.", opts: ["decision", "deciding", "decisive", "decided"], ans: 0 },
      { q: "Choose the adjective form of 'danger'.", opts: ["danger", "dangerous", "endanger", "dangerously"], ans: 1 },
      { q: "Choose the verb form of 'movement'.", opts: ["move", "moving", "moved", "moves"], ans: 0 },
      { q: "Choose the noun form of 'perform'.", opts: ["performance", "performer", "performing", "performs"], ans: 0 },
      { q: "Choose the adjective form of 'beauty'.", opts: ["beautiful", "beautify", "beautified", "beauty"], ans: 0 },
      { q: "Choose the adverb form of 'quick'.", opts: ["quicker", "quickness", "quickly", "quicken"], ans: 2 },
      { q: "Choose the verb form of 'discussion'.", opts: ["discuss", "discussing", "discussed", "discusses"], ans: 0 },
      { q: "Choose the noun form of 'educate'.", opts: ["education", "educating", "educated", "educator"], ans: 0 },
      { q: "Choose the adjective form of 'health'.", opts: ["heal", "healthy", "healthily", "healthful"], ans: 1 },
      { q: "Choose the noun form of 'grow'.", opts: ["grown", "grew", "growth", "growing"], ans: 2 },
      { q: "Choose the adverb form of 'happy'.", opts: ["happiness", "happily", "happier", "happy"], ans: 1 },
      { q: "Choose the adjective form of 'create'.", opts: ["creative", "creation", "creator", "creatively"], ans: 0 },
      { q: "Choose the noun form of 'strong'.", opts: ["strength", "stronger", "strongly", "strongest"], ans: 0 },
      { q: "Choose the verb form of 'speech'.", opts: ["speak", "spoken", "speaking", "speaks"], ans: 0 },
      { q: "Choose the adjective form of 'music'.", opts: ["musical", "musician", "musically", "music"], ans: 0 }
    ],

    "vocab-phrasal-verbs": [
      { q: "I need to _____ my homework before dinner.", opts: ["give up", "take off", "finish up", "look after"], ans: 2 },
      { q: "She looks _____ her younger brother.", opts: ["at", "after", "over", "through"], ans: 1 },
      { q: "Please _____ the lights when you leave.", opts: ["turn off", "put down", "get off", "take out"], ans: 0 },
      { q: "He _____ smoking last year.", opts: ["gave away", "gave up", "got out", "went off"], ans: 1 },
      { q: "Let’s _____ the problem together.", opts: ["work out", "set off", "turn in", "put up"], ans: 0 },
      { q: "We need to _____ early to catch the train.", opts: ["set out", "run away", "break down", "call off"], ans: 0 },
      { q: "Can you _____ the form, please?", opts: ["fill in", "write off", "go over", "break in"], ans: 0 },
      { q: "He _____ a new idea during the meeting.", opts: ["got through", "came up with", "fell behind", "turned out"], ans: 1 },
      { q: "Don’t _____ your dreams!", opts: ["give up", "go on", "get by", "turn up"], ans: 0 },
      { q: "We ran _____ sugar, so I went to buy some.", opts: ["in", "on", "out of", "down"], ans: 2 },
      { q: "The plane will _____ in 30 minutes.", opts: ["take off", "turn up", "check in", "set up"], ans: 0 },
      { q: "I _____ my old school friend at the mall.", opts: ["ran into", "took over", "got through", "came across"], ans: 0 },
      { q: "Please _____ your shoes before entering.", opts: ["take off", "put out", "get on", "hand in"], ans: 0 },
      { q: "He _____ the challenge and succeeded.", opts: ["came over", "took on", "looked into", "ran over"], ans: 1 },
      { q: "We had to _____ the event due to rain.", opts: ["call off", "get on", "carry on", "put off"], ans: 0 }
    ],
    "listening": [
      { q: "What did the speaker say about the weather?", opts: ["It's sunny", "It's raining", "It's cloudy", "It's snowing"], ans: 1 },
  { q: "Where is the woman going?", opts: ["Home", "School", "Market", "Office"], ans: 3 },
  { q: "Woman: I'm hungry. \nMan: Let's grab lunch.\nWhat will they probably do?", opts: ["Go home", "Eat out", "Go shopping", "Take a walk"], ans: 1 },
  { q: "Man: Did you do the homework? \nWoman: Not yet.\nWhat does the woman mean?", opts: ["She finished it", "She forgot it", "She hasn’t done it", "She lost it"], ans: 2 },
  { q: "What time is the meeting?", opts: ["9 AM", "10 AM", "11 AM", "Noon"], ans: 2 },
  { q: "What did the man forget?", opts: ["His bag", "His phone", "His keys", "His book"], ans: 0 },
  { q: "Man: I failed the test. \nWoman: That’s too bad.\nHow does the woman feel?", opts: ["Excited", "Sorry", "Angry", "Happy"], ans: 1 },
  { q: "Woman: Where's the bus stop? \nMan: Just around the corner.\nWhat is the man doing?", opts: ["Giving directions", "Calling a bus", "Waiting", "Running"], ans: 0 },
  { q: "How did the man travel?", opts: ["By car", "By train", "By plane", "By bike"], ans: 2 },
  { q: "What’s the speaker's job?", opts: ["Teacher", "Waiter", "Doctor", "Engineer"], ans: 0 },
  { q: "What does the woman suggest?", opts: ["Go early", "Skip it", "Reschedule", "Bring a friend"], ans: 0 },
  { q: "Man: See you tomorrow. \nWoman: Same time?\nWhat are they talking about?", opts: ["A meeting", "A trip", "A phone call", "A class"], ans: 0 },
  { q: "Woman: I passed my exam! \nMan: Congratulations!\nHow does the man feel?", opts: ["Proud", "Excited", "Happy for her", "Angry"], ans: 2 },
  {q: "Where is the speaker?", opts: ["In a store", "At a park", "On a bus", "At a restaurant"], ans: 3 },
  { q: "How does the speaker feel?", opts: ["Excited", "Angry", "Tired", "Sad"], ans: 2 },
  { q: "Why did the boy go to the forest?", opts: ["To play", "To find treasure", "To look for his dog", "To meet a friend"], ans: 2 },
      { q: "What did Sara find in the attic?", opts: ["A letter", "A photo", "A box", "A map"], ans: 0 },
      { q: "Who helped the old man in the story?", opts: ["His son", "A stranger", "His friend", "A nurse"], ans: 1 },
      { q: "What was the main problem in the story?", opts: ["Lost keys", "A storm", "A flat tire", "A broken phone"], ans: 1 },
      { q: "What happened at the end of the story?", opts: ["They left", "They won", "They got lost", "They went home"], ans: 3 },
      { q: "Where did the story take place?", opts: ["A farm", "A school", "A forest", "A city"], ans: 2 },
      { q: "What was the girl afraid of?", opts: ["Spiders", "The dark", "Loud noises", "Heights"], ans: 1 },
      { q: "What lesson did the story teach?", opts: ["Be kind", "Be fast", "Be smart", "Be rich"], ans: 0 },
      { q: "What did they do when it rained?", opts: ["Went home", "Danced", "Ran", "Took shelter"], ans: 3 },
      { q: "How did the dog save the family?", opts: ["By barking", "By finding help", "By waking them", "By staying quiet"], ans: 1 },
      { q: "What did the man forget?", opts: ["His hat", "His wallet", "His phone", "His ticket"], ans: 3 },
      { q: "Who was the main character?", opts: ["A student", "A teacher", "A king", "A farmer"], ans: 0 },
      { q: "Why did the girl cry?", opts: ["She was hurt", "She was scared", "She lost her toy", "She was angry"], ans: 2 },
      { q: "How did they escape?", opts: ["Through a window", "By running", "With help", "By hiding"], ans: 0 },
      { q: "What was the surprise ending?", opts: ["They moved", "It was a dream", "She woke up", "The prize was fake"], ans: 1 },
      { q: "How are you?", opts: ["Yes, please.", "I’m fine, thanks.", "See you later.", "No, I don’t."], ans: 1 },
      { q: "What time is it?", opts: ["It's raining.", "It’s 3 o'clock.", "I'm tired.", "In the morning."], ans: 1 },
      { q: "Do you like pizza?", opts: ["Yes, I do.", "No, I am not.", "I have it.", "I like pasta."], ans: 0 },
      { q: "Where are you from?", opts: ["I’m 20.", "From India.", "I’m tall.", "Yes, I am."], ans: 1 },
      { q: "What do you do?", opts: ["I do well.", "I’m a student.", "Yes, I do.", "It’s done."], ans: 1 },
      { q: "Can I help you?", opts: ["I’m helping.", "I don’t know.", "Yes, I need a pen.", "It’s okay."], ans: 2 },
      { q: "What’s your name?", opts: ["Fine, thanks.", "I’m John.", "I’m here.", "Yes, please."], ans: 1 },
      { q: "Do you have a pencil?", opts: ["Yes, here it is.", "I’m reading.", "It’s small.", "Later."], ans: 0 },
      { q: "How old are you?", opts: ["I’m fine.", "I’m 18.", "Yes, I am.", "Tomorrow."], ans: 1 },
      { q: "Is this your book?", opts: ["Yes, it is.", "No, I do.", "I read.", "He has one."], ans: 0 },
      { q: "Where is the bathroom?", opts: ["At 10 PM.", "It’s upstairs.", "It's a room.", "Yes, it is."], ans: 1 },
      { q: "Do you speak English?", opts: ["No, I’m not.", "Yes, I do.", "I'm English.", "Here it is."], ans: 1 },
      { q: "Are you ready?", opts: ["Yes, I am.", "Yes, I do.", "I will go.", "Not very."], ans: 0 },
      { q: "What day is it today?", opts: ["It’s Monday.", "At school.", "It’s hot.", "No idea."], ans: 0 },
      { q: "Would you like some tea?", opts: ["Yes, I would.", "Yes, I am.", "No, I can’t.", "I am tea."], ans: 0 }
    ],

    "listening-short-conversations": [
      { q: "What did the speaker say about the weather?", opts: ["It's sunny", "It's raining", "It's cloudy", "It's snowing"], ans: 1 },
  { q: "Where is the woman going?", opts: ["Home", "School", "Market", "Office"], ans: 3 },
  { q: "Woman: I'm hungry. \nMan: Let's grab lunch.\nWhat will they probably do?", opts: ["Go home", "Eat out", "Go shopping", "Take a walk"], ans: 1 },
  { q: "Man: Did you do the homework? \nWoman: Not yet.\nWhat does the woman mean?", opts: ["She finished it", "She forgot it", "She hasn’t done it", "She lost it"], ans: 2 },
  { q: "What time is the meeting?", opts: ["9 AM", "10 AM", "11 AM", "Noon"], ans: 2 },
  { q: "What did the man forget?", opts: ["His bag", "His phone", "His keys", "His book"], ans: 0 },
  { q: "Man: I failed the test. \nWoman: That’s too bad.\nHow does the woman feel?", opts: ["Excited", "Sorry", "Angry", "Happy"], ans: 1 },
  { q: "Woman: Where's the bus stop? \nMan: Just around the corner.\nWhat is the man doing?", opts: ["Giving directions", "Calling a bus", "Waiting", "Running"], ans: 0 },
  { q: "How did the man travel?", opts: ["By car", "By train", "By plane", "By bike"], ans: 2 },
  { q: "What’s the speaker's job?", opts: ["Teacher", "Waiter", "Doctor", "Engineer"], ans: 0 },
  { q: "What does the woman suggest?", opts: ["Go early", "Skip it", "Reschedule", "Bring a friend"], ans: 0 },
  { q: "Man: See you tomorrow. \nWoman: Same time?\nWhat are they talking about?", opts: ["A meeting", "A trip", "A phone call", "A class"], ans: 0 },
  { q: "Woman: I passed my exam! \nMan: Congratulations!\nHow does the man feel?", opts: ["Proud", "Excited", "Happy for her", "Angry"], ans: 2 },
  {q: "Where is the speaker?", opts: ["In a store", "At a park", "On a bus", "At a restaurant"], ans: 3 },
  { q: "How does the speaker feel?", opts: ["Excited", "Angry", "Tired", "Sad"], ans: 2 }
    ],
    "listening-stories": [
      { q: "Why did the boy go to the forest?", opts: ["To play", "To find treasure", "To look for his dog", "To meet a friend"], ans: 2 },
      { q: "What did Sara find in the attic?", opts: ["A letter", "A photo", "A box", "A map"], ans: 0 },
      { q: "Who helped the old man in the story?", opts: ["His son", "A stranger", "His friend", "A nurse"], ans: 1 },
      { q: "What was the main problem in the story?", opts: ["Lost keys", "A storm", "A flat tire", "A broken phone"], ans: 1 },
      { q: "What happened at the end of the story?", opts: ["They left", "They won", "They got lost", "They went home"], ans: 3 },
      { q: "Where did the story take place?", opts: ["A farm", "A school", "A forest", "A city"], ans: 2 },
      { q: "What was the girl afraid of?", opts: ["Spiders", "The dark", "Loud noises", "Heights"], ans: 1 },
      { q: "What lesson did the story teach?", opts: ["Be kind", "Be fast", "Be smart", "Be rich"], ans: 0 },
      { q: "What did they do when it rained?", opts: ["Went home", "Danced", "Ran", "Took shelter"], ans: 3 },
      { q: "How did the dog save the family?", opts: ["By barking", "By finding help", "By waking them", "By staying quiet"], ans: 1 },
      { q: "What did the man forget?", opts: ["His hat", "His wallet", "His phone", "His ticket"], ans: 3 },
      { q: "Who was the main character?", opts: ["A student", "A teacher", "A king", "A farmer"], ans: 0 },
      { q: "Why did the girl cry?", opts: ["She was hurt", "She was scared", "She lost her toy", "She was angry"], ans: 2 },
      { q: "How did they escape?", opts: ["Through a window", "By running", "With help", "By hiding"], ans: 0 },
      { q: "What was the surprise ending?", opts: ["They moved", "It was a dream", "She woke up", "The prize was fake"], ans: 1 }
    ],
    "listening-questions-&-responses": [
      { q: "How are you?", opts: ["Yes, please.", "I’m fine, thanks.", "See you later.", "No, I don’t."], ans: 1 },
      { q: "What time is it?", opts: ["It's raining.", "It’s 3 o'clock.", "I'm tired.", "In the morning."], ans: 1 },
      { q: "Do you like pizza?", opts: ["Yes, I do.", "No, I am not.", "I have it.", "I like pasta."], ans: 0 },
      { q: "Where are you from?", opts: ["I’m 20.", "From India.", "I’m tall.", "Yes, I am."], ans: 1 },
      { q: "What do you do?", opts: ["I do well.", "I’m a student.", "Yes, I do.", "It’s done."], ans: 1 },
      { q: "Can I help you?", opts: ["I’m helping.", "I don’t know.", "Yes, I need a pen.", "It’s okay."], ans: 2 },
      { q: "What’s your name?", opts: ["Fine, thanks.", "I’m John.", "I’m here.", "Yes, please."], ans: 1 },
      { q: "Do you have a pencil?", opts: ["Yes, here it is.", "I’m reading.", "It’s small.", "Later."], ans: 0 },
      { q: "How old are you?", opts: ["I’m fine.", "I’m 18.", "Yes, I am.", "Tomorrow."], ans: 1 },
      { q: "Is this your book?", opts: ["Yes, it is.", "No, I do.", "I read.", "He has one."], ans: 0 },
      { q: "Where is the bathroom?", opts: ["At 10 PM.", "It’s upstairs.", "It's a room.", "Yes, it is."], ans: 1 },
      { q: "Do you speak English?", opts: ["No, I’m not.", "Yes, I do.", "I'm English.", "Here it is."], ans: 1 },
      { q: "Are you ready?", opts: ["Yes, I am.", "Yes, I do.", "I will go.", "Not very."], ans: 0 },
      { q: "What day is it today?", opts: ["It’s Monday.", "At school.", "It’s hot.", "No idea."], ans: 0 },
      { q: "Would you like some tea?", opts: ["Yes, I would.", "Yes, I am.", "No, I can’t.", "I am tea."], ans: 0 }
    ]
    
  };
  